# -*- mode: org -*-
# -*- coding: utf-8 -*-
#+STARTUP: overview indent inlineimages logdrawer

#+TITLE: @@latex: Ciência Reprodutível para Experimentos em \\
#+TITLE: Computação de Alto Desempenho@@
#+AUTHOR:
#+LANGUAGE: bt-br
#+TAGS: noexport(n) ignore(i)
#+EXPORT_SELECT_TAGS: Blog
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+COLUMNS: %25ITEM %TODO %3PRIORITY %TAGS
#+SEQ_TODO: TODO(t!) STARTED(s!) WAITING(w@) APPT(a!) | DONE(d!) CANCELLED(c!) DEFERRED(f!)

* LaTeX Configuration                                       :noexport:ignore:
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt]

:latex_headers:
#+LATEX_HEADER: \usepackage{sbc-template}
#+LATEX_HEADER: \usepackage{amsmath,amsfonts,amssymb,amsthm}
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{DejaVuSansMono}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage{array}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage[brazilian]{babel}
#+LATEX_HEADER: \usepackage[scale=2]{ccicons}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{relsize}
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \usepackage{wasysym}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \lstset{ %
#+LATEX_HEADER:   backgroundcolor={},
#+LATEX_HEADER:   basicstyle=\ttfamily\tiny,
#+LATEX_HEADER:   breakatwhitespace=true,
#+LATEX_HEADER:   breaklines=true,
#+LATEX_HEADER:   captionpos=b,
#+LATEX_HEADER:   extendedchars=true,
#+LATEX_HEADER:   frame=n,
#+LATEX_HEADER:   numbers=left,
#+LATEX_HEADER:   rulecolor=\color{black},
#+LATEX_HEADER:   showspaces=false,
#+LATEX_HEADER:   showstringspaces=false,
#+LATEX_HEADER:   showtabs=false,
#+LATEX_HEADER:   stepnumber=1,
#+LATEX_HEADER:   stringstyle=\color{gray},
#+LATEX_HEADER:   tabsize=2,
#+LATEX_HEADER: }
#+LATEX_HEADER: \renewcommand*{\UrlFont}{\ttfamily\smaller\relax}
#+LATEX_HEADER: \author{
#+LATEX_HEADER:    Pedro Bruel\inst{1},
#+LATEX_HEADER:    Lucas Mello Schnorr\inst{2},
#+LATEX_HEADER:    Alfredo Goldman\inst{1}}
#+LATEX_HEADER: \address{
#+LATEX_HEADER:    Universidade de São Paulo (USP)
#+LATEX_HEADER:    \nextinstitute
#+LATEX_HEADER:    Universidade Federal do Rio Grande do Sul (UFRGS)
#+LATEX_HEADER:    \email{\{phrb,gold\}@ime.usp.br, schnorr@inf.ufrgs.br}}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks=true,
#+LATEX_HEADER:     linkcolor={black},
#+LATEX_HEADER:     citecolor={black},
#+LATEX_HEADER:     urlcolor={black}
#+LATEX_HEADER: }

#+LATEX_HEADER: \usepackage[style=numeric,backend=bibtex]{biblatex}
#+LATEX_HEADER: \addbibresource{references.bib}
:end:

* Rascunho                                                  :noexport:ignore:
** Mensagem principal
1. A reprodutibilidade é fundamental para a produção de ciência experimental
2. Para a reprodutibilidade, são fundamentais:
   - Noções básicas de estatística (incluindo desenho de experimentos)
   - Registro contínuo (o caderno de laboratório)
   - Controle de versão para texto, código,  e dados (suficiente para Ciência da
     Computação? E o Hardware?)
   - Abertura  e registro  dos  dados  e análises  (diferente  da hospedagem  no
     GitHub, etc)

A partir  disso, nosso  texto pode apresentar  alguns conceitos  de estatística,
apontando  para fontes  de aprofundamento,  e algumas  ferramentas interessantes
para  implementar o  registro contínuo,  o controle  de versão,  e o  registro e
disponibilização de dados. No fim, apresentamos algum exemplo prático em Ciência
da Computação.  No ERAD-SP, apresentamos  algo relacionado a Computação  de Alto
Desempenho.

* Resumo                                                             :ignore:
#+begin_export latex
\begin{abstract}
  Neste  minicurso   apresentaremos  uma  introdução  à   Ciência  Reprodutível,
  orientada por discussões  sobre os problemas comumente  enfrentados na ciência
  experimental,  e  por  apresentações  de possíveis  soluções  que  promovam  a
  reprodutibilidade no contexto de experimentos computacionais.
\end{abstract}
#+end_export

* Introdução
O  objetivo  deste minicurso  é  promover  e  difundir conceitos  e  ferramentas
associados à produção de Ciência Reprodutível para experimentos em Computação de
Alto  Desempenho.   Os  participantes  devem  ter  familiaridade  com  conceitos
introdutórios de linguagens  de programação. Fundamentos de  estatística não são
estritamente  necessários, mas  podem aumentar  o aproveitamento  das discussões
sobre análise de resultados.

Grande  parte da  pesquisa em  Computação  de Alto  Desempenho envolve  métricas
associadas a  software ou  hardware, como  o tempo  de execução  e o  consumo de
memória e energia. Além disso, a coleta e a análise estatística de dados é parte
fundamental da  argumentação construída  a partir dos  resultados. Como  em toda
parte empírica da ciência, é crucial garantir a reprodutibilidade da pesquisa em
Computação  de  Alto Desempenho,  e  consideramos  portanto  que este  tópico  é
bastante relevante para a Escola Regional de Alto Desempenho.

Propomos uma  apresentação de  duas horas,  cujo público  alvo são  estudantes e
pesquisadores realizando  iniciação científica, mestrado, e  doutorado, em áreas
que envolvam experimentos computacionais.   Os recursos estritamente necessários
para este curso são apenas o acesso à internet.

Este documento é  organizado como descrito a  seguir.  A Seção\nbsp{}[[Proponentes]]
apresenta biografias  curtas dos proponentes, e  a Seção\nbsp{}[[Tópicos Abordados]]
apresenta detalhes sobre os tópicos abordados no minicurso.

* Proponentes
*Alfredo Goldman*  é Professor  Associado na  Universidade de  São Paulo.  Ele é
editor de  área de concentração  na revista  Parallel Computing, e  participa no
comitê  de  programa  de  conferências  como XP,  IPDPS,  IEEE-NCA,  SC,  JSSPP,
SBAC-PAD,  SBRC,  SBES  e  SBQS.  Seus interesses  principais  de  pesquisa  são
Computação Paralela e Distribuída, Escalonamento, e Métodos Ágeis.

*Lucas Mello Schnorr* é Professor Associado no Instituto de Informática da Universidade
Federal do Rio Grande do Sul (UFRGS). Seus interesses principais de pesquisa são
Análise de Desempenho, Simulação de Sistemas Computacionais de Alto Desempenho,
e Ciência de Dados.

*Pedro Bruel* é aluno de doutorado na  Universidade de São Paulo e na Université
de Grenoble Alpes, França, orientado  pelos professores Alfredo Goldman e Arnaud
Legrand.   Seu interesses  principais de  pesquisa  são Modelagem  e Análise  de
Desempenho para Computação de Alto Desempenho.

* Tópicos Abordados
O minicurso  é estruturado como  segue.  Primeiro, motivaremos  e apresentaremos
Ciência  Reprodutível no  contexto da  Ciência da  Computação, como  descrito na
Seção\nbsp{}[[O   que   é   Ciência  Reprodutível?]].    Depois,   discutiremos   na
Seção\nbsp{}[[Problemas:   É  possível   fazer  Computação   de  Alto   Desempenho
Reprodutível?]]  os principais empecilhos para se fazer experimentos reprodutíveis
em   Computação   de   Alto   Desempenho,   e   em   seguida   discutiremos   na
Seção\nbsp{}[[Soluções:  Ferramentas  para Reprodutibilidade]]  algumas  estratégias
para contornar ou resolver os problemas levantados.

** O que é Ciência Reprodutível?
Conclusões produzidas a partir de  dados obtidos experimentalmente não podem ser
consideradas  validadas  até  que   seja  possível  reproduzi-las  em  condições
experimentais independentes. Esse princípio  orienta todo o progresso científico
baseado em  metodologias experimentais.  A  pesquisa experimental em  Ciência da
Computação está em posição singular para reforçar e promover a reprodutibilidade
científica,  pois experimentos  computacionais em  determinados casos  podem ser
acompanhados,  registrados, e  repetidos  com precisão  e controle  praticamente
impossíveis em áreas  como a biologia e  a química.  As organizações  em prol da
ciência brasileira têm portanto grandes  justificativas para promover e reforçar
a reprodutibilidade científica.

Os esforços da  ACM\nbsp{}\cite{acm2021badging} são um bom  exemplo dos esforços
iniciais  que  podem ser  realizados  em  prol da  reprodutibilidade.   Diversas
conferências e  periódicos da  ACM adotam  um sistema  de insígnias  para marcar
trabalhos  cujos  esforços  para  reprodutibilidade  de  seus  experimentos  são
significativos.  A  nomenclatura utilizada  pela ACM  é derivada  do Vocabulário
Internacional   de    Metrologia   (VIM)\nbsp{}\cite{bipm2012international},   e
distingue entre resultados e conclusões que podem ser reproduzidos:

- Pela mesma equipe, nas mesmas condições experimentais (Repetibilidade)
- Por uma equipe diferente, nas mesmas condições experimentais (Replicabilidade)
- Por   uma   equipe   diferente,    em   condições   experimentais   diferentes
  (Reprodutibilidade)

O código e os dados que dão  suporte às conclusões de um estudo científico devem
ser submetidos  junto ao  documento que será  publicado.  Esses  /artefatos/ são
avaliados pelos  revisores e insígnias são  conferidas de acordo com  o nível de
reprodutibilidade   alcançado.    Outras    organizações   também   promovem   a
reprodutibilidade,    como   a    ReScience\nbsp{}\cite{rescience2021faq},   que
recentemente      promoveu      o      Desafio      de      10      Anos      da
Reprodutibilidade\nbsp{}\cite{rescience2020ten},   onde    pesquisadores   foram
incentivados a submeter artigos com a  reprodução de seus próprios resultados de
no mínimo 10 anos de idade.

Ações  como as  tomadas pela  ACM  podem ter  um  grande impacto  no reforço  da
credibilidade  do método  científico e  no  avanço da  descoberta científica  no
Brasil.
** Problemas: É possível fazer Computação de Alto Desempenho Reprodutível?
Abaixo  listamos  alguns dos  problemas  que  vamos apresentar,  relacionados  a
experimentos com Computação de Alto Desempenho.

- Custo elevado
- Arquiteturas muito específicas
  - Baixa disponibilidade
- Software muito complexo
  - Tempo de execução
  - Consumo de energia
- Ciência fechada
  - O financiamento é público, mas o acesso é fechado
- Análise Estatística e Desenho de Experimentos
  - Desenho de Experimentos
  - Nem sempre é claro ou fácil analisar os resultados
  - Quando precisamos de /Machine Learning/?

** Soluções: Ferramentas para Reprodutibilidade
Abaixo listamos algumas das soluções que vamos discutir:

- Virtualização
  - Docker, Singularity, \dots
- Controle de versão
  - Git, \dots
  - Hospedagem: GitHub, Gitlab, \dots
- Documentos computacionais
  - Orgmode, notebook Jupyter, Rmarkdown, \dots
- Arquivamento de dados, código, relatórios
  - Zenodo, software heritage, \dots
- Ciência fechada
  - Arxiv, preprints, scihub, libgen
- Análise Estatística e Desenho de Experimentos
  - Desenho de Experimentos: Coletar dados para testar hipóteses de forma eficiente
  - Regressão Linear, ANOVA: Análises mais poderosas do que parecem
  - Ferramentas na linguagem R, Julia, Python, \dots

* Referências                                                        :ignore:
#+begin_export latex
\printbibliography[heading=bibintoc]
#+end_export
